on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: 'x86'
          distribution: 'minimal'
          version: '8.9'
          packages: 'rackcheck'
      - name: Run Tests
        run: raco test main.rkt

